forecastapp:
    bigquery:
      full_table_id: "ms_forecast_custom."
      project_id: "ms-data-warehouse"
      q_check_contents: """SELECT max(last_system_update_date) as last_system_update_date FROM  """
    app:
      access_hv_token: "*******************************************************************************"
      hv_id: "681274"
      url_api: "https://api.forecastapp.com/"
      schemas: ['assignments', 'clients', 'projects', 'placeholders', 'people']
harvest:
    bigquery:
      full_table_id: "ms_forecast_custom."
      project_id: "ms-data-warehouse"
      q_check_contents: """SELECT max(last_system_update_date) as last_system_update_date FROM  """
    app:
      access_hv_token: "*******************************************************************************"
      hv_id: "681274"
      url_api: "https://api.forecastapp.com/"
      schemas: ['assignments', 'clients', 'projects', 'placeholders', 'people']
