forecastapp:
    bigquery:
      full_table_id: "ms_forecast_custom."
      project_id: "ms-data-warehouse"
      q_check_contents: """SELECT max(last_system_update_date) as last_system_update_date FROM  """
    app:
      access_hv_token: "2366395.pt.o0uOxxspBcIf8hhHVmY9s_OPp1XSwSBzZMyiDJ20Krqv8l_zU0vCHpCgOr1hsMLielP8OfNvzbmthdMsR80gHA"
      hv_id: "681274"
      url_api: "https://api.forecastapp.com/"
      schemas: ['assignments', 'clients', 'projects', 'placeholders', 'people']
harvest:
    bigquery:
      full_table_id: "ms_forecast_custom."
      project_id: "ms-data-warehouse"
      q_check_contents: """SELECT max(last_system_update_date) as last_system_update_date FROM  """
    app:
      access_hv_token: "2366395.pt.o0uOxxspBcIf8hhHVmY9s_OPp1XSwSBzZMyiDJ20Krqv8l_zU0vCHpCgOr1hsMLielP8OfNvzbmthdMsR80gHA"
      hv_id: "681274"
      url_api: "https://api.forecastapp.com/"
      schemas: ['assignments', 'clients', 'projects', 'placeholders', 'people']